using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CASOS_DE_USO.AUDITORIA
{
    public class OPERACIONES_AUDITORIA
    {
        public static void AGREGAR_AUDITORIA(CONTEXTO.CLINICA_AZMED AZMED_CLINICA, MODELO.AUDITORIA_LOGIN_LOGOUT AUDITORIA)
        {
            AZMED_CLINICA.AUDITORIA.Add(AUDITORIA);
        }

        public static void MODIFICAR_AUDITORIA(CONTEXTO.CLINICA_AZMED AZMED_CLINICA, MODELO.AUDITORIA_LOGIN_LOGOUT AUDITORIA)
        {
            AZMED_CLINICA.Entry(AUDITORIA).State = System.Data.Entity.EntityState.Modified;
        }

        public static void ELIMINAR_AUDITORIA(CONTEXTO.CLINICA_AZMED AZMED_CLINICA, MODELO.AUDITORIA_LOGIN_LOGOUT AUDITORIA)
        {
            AZMED_CLINICA.AUDITORIA.Remove(AUDITORIA);
        }

        public static void AGREGAR_AUDITORIA_USUARIO(CONTEXTO.CLINICA_AZMED AZMED_CLINICA, MODELO.AUDITORIA_USUARIO AUDITORIA_USUARIO)
        {
            AZMED_CLINICA.AUDITORIA_USUARIO.Add(AUDITORIA_USUARIO);
        }

        public static void MODIFICAR_AUDITORIA_USUARIO(CONTEXTO.CLINICA_AZMED AZMED_CLINICA, MODELO.AUDITORIA_USUARIO AUDITORIA_USUARIO)
        {
            AZMED_CLINICA.Entry(AUDITORIA_USUARIO).State = System.Data.Entity.EntityState.Modified;
        }

        public static void ELIMINAR_AUDITORIA_USUARIO(CONTEXTO.CLINICA_AZMED AZMED_CLINICA, MODELO.AUDITORIA_USUARIO AUDITORIA_USUARIO)
        {
            AZMED_CLINICA.AUDITORIA_USUARIO.Remove(AUDITORIA_USUARIO);
        }
    }
}
