// <auto-generated />
namespace CONTEXTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ESPECIALIDADES_USUARIOS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ESPECIALIDADES_USUARIOS));
        
        string IMigrationMetadata.Id
        {
            get { return "202202172336301_ESPECIALIDADES_USUARIOS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
