// <auto-generated />
namespace CONTEXTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ELIMINAR_IDROL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ELIMINAR_IDROL));
        
        string IMigrationMetadata.Id
        {
            get { return "202202151421324_ELIMINAR_IDROL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
