// <auto-generated />
namespace CONTEXTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DIA_MODELO_STRING : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DIA_MODELO_STRING));
        
        string IMigrationMetadata.Id
        {
            get { return "202203120043520_DIA_MODELO_STRING"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
