// <auto-generated />
namespace CONTEXTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IMPORTE_ESPECIALIDAD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IMPORTE_ESPECIALIDAD));
        
        string IMigrationMetadata.Id
        {
            get { return "202203172234452_IMPORTE_ESPECIALIDAD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
