// <auto-generated />
namespace CONTEXTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CAMBIO_MODELO_ATENCION : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CAMBIO_MODELO_ATENCION));
        
        string IMigrationMetadata.Id
        {
            get { return "202202220327575_CAMBIO_MODELO_ATENCION"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
