// <auto-generated />
namespace CONTEXTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OBRA_SOCIAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OBRA_SOCIAL));
        
        string IMigrationMetadata.Id
        {
            get { return "202202121728297_OBRA_SOCIAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
