// <auto-generated />
namespace CONTEXTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AGREGO_TABLAS_PACIENTE_PROFESIONAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AGREGO_TABLAS_PACIENTE_PROFESIONAL));
        
        string IMigrationMetadata.Id
        {
            get { return "202302011702560_AGREGO_TABLAS_PACIENTE_PROFESIONAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
